#!/bin/sh
#
# $FreeBSD$

# PROVIDE: vm
# REQUIRE: NETWORKING SERVERS DAEMON LOGIN
# KEYWORD: shutdown nojail

. /etc/rc.subr

name=vm
desc="Start and stop vm-bhyve guests on boot/shutdown"
rcvar=vm_enable

load_rc_config $name

command="/usr/local/sbin/${name}"
start_cmd="${name}_start"
stop_cmd="${command} stopall"

vm_start()
{
	${command} init
	${command} startall >/dev/null &
}

run_rc_command "$1"
